### ISSUE TITLE
Thème Mozilla

### ISSUE THREAD

**Issue by MatonAnthony** [mozfr/firefoxosminisite#22]
Le blog (beta.firefoxos.mozfr.org/blog) est actuellement identique au design officiel Mozilla, il doit absolument être différent du design officiel.
- [ ] Marquer une différenciation nette entre ce blog et les blogs officiels Mozilla
- [x] Traduire les quelques pages d'erreur (Elles sont pas sur github, mais peuvent être à disposition de celui qui veut s'en occuper)
  Du coup, si nos amis de la comm' pouvait nous donner des idées de ce qui vous plairait niveau changement. Je pense pas qu'on ait des designers, mais on peut essayer de vous proposer un truc !

**Comment by SphinxKnight** [comment]
Petit ange parti tro tôt 
RT si t tris
